name = "just-sticky-notes"
main = "functions/_worker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "just-sticky-notes"

[[r2_buckets]]
binding = "STICKY_NOTES_BUCKET"
bucket_name = "just-sticky-notes-data"

[durable_objects]
bindings = [
  { name = "STICKY_NOTES_DO", class_name = "StickyNotesRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["StickyNotesRoom"]

[vars]
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = "" 